# Generated by Django 5.1.3 on 2024-12-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rutina_delete_mi_rutina_remove_alumno_profesion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='Plan_vigente',
        ),
        migrations.AddField(
            model_name='alumno',
            name='plan',
            field=models.CharField(choices=[('musculacion', 'Musculación'), ('yoga', 'Yoga'), ('crossfit', 'Crossfit'), ('funcional', 'Entrenamiento Funcional'), ('pilates', 'Pilates'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
