# Generated by Django 5.1.3 on 2024-12-10 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_alumno_plan_vigente_alumno_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='fecha_creacion',
        ),
        migrations.CreateModel(
            name='MiRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('ejercicio', models.CharField(max_length=255)),
                ('series', models.PositiveIntegerField(default=3)),
                ('repeticiones', models.PositiveIntegerField(default=12)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='app.alumno')),
            ],
            options={
                'ordering': ['dia', 'ejercicio'],
            },
        ),
    ]
