# Generated by Django 5.1.3 on 2024-12-10 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_rutina_fecha_creacion_mirutina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('series', models.PositiveIntegerField(default=3)),
                ('repeticiones', models.PositiveIntegerField(default=12)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RutinaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('ejercicios', models.ManyToManyField(to='app.ejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='RutinaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_semanales', to='app.alumno')),
                ('domingo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domingo', to='app.rutinadiaria')),
                ('jueves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jueves', to='app.rutinadiaria')),
                ('lunes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunes', to='app.rutinadiaria')),
                ('martes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='martes', to='app.rutinadiaria')),
                ('miercoles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miercoles', to='app.rutinadiaria')),
                ('sabado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabado', to='app.rutinadiaria')),
                ('viernes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viernes', to='app.rutinadiaria')),
            ],
            options={
                'ordering': ['alumno'],
            },
        ),
        migrations.DeleteModel(
            name='MiRutina',
        ),
    ]
