# Generated by Django 5.1.3 on 2024-12-22 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ejercicio_rutinadiaria_rutinasemanal_delete_mirutina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutinasemanal',
            name='viernes',
        ),
        migrations.RemoveField(
            model_name='rutinasemanal',
            name='lunes',
        ),
        migrations.RemoveField(
            model_name='rutinasemanal',
            name='miercoles',
        ),
        migrations.RemoveField(
            model_name='rutinasemanal',
            name='martes',
        ),
        migrations.RemoveField(
            model_name='rutinasemanal',
            name='sabado',
        ),
        migrations.RemoveField(
            model_name='rutinasemanal',
            name='domingo',
        ),
        migrations.RemoveField(
            model_name='rutinasemanal',
            name='jueves',
        ),
        migrations.RemoveField(
            model_name='rutinasemanal',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='repeticiones',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='series',
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RutinaDiaria',
        ),
        migrations.DeleteModel(
            name='RutinaSemanal',
        ),
    ]
